/**
 * Development-only Astro adapter for the Maofuxing DSH visual editor.
 *
 * A Vite plugin injects source markers onto literal Astro elements. An inert
 * bootstrap loads the picker only inside the DSH editor or when the explicit
 * `dsh-visual-editor=1` query parameter is present.
 */

import { parse as parseAstro } from '@astrojs/compiler'
import MagicString from 'magic-string'
import { createHash } from 'node:crypto'
import { basename, relative, resolve } from 'node:path'

export const DEFAULT_DSH_HOST = 'http://127.0.0.1:43120'

/**
 * Atomic source edits create short-lived sibling directories such as
 * `.index.astro.<pid>.<uuid>.tmpdir`. On Windows, Node's native watcher can
 * try to subscribe before the directory disappears and surface an EBUSY
 * rejection in Astro's error overlay.
 */
export const DSH_ATOMIC_WRITE_WATCH_IGNORES = [
  '**/.*.tmpdir',
  '**/.*.tmpdir/**',
] as const

export interface DshVisualEditorOptions {
  /** Absolute project root; defaults to the importing process directory. */
  projectRoot?: string
  /** DSH loopback Host origin serving the picker and selection routes. */
  host?: string
}

/** Minimal structural surface of Astro's `astro:config:setup` context. */
interface AstroConfigSetupContext {
  command: 'dev' | 'build' | 'preview'
  config: { devToolbar?: { enabled?: boolean } }
  updateConfig(config: {
    vite?: {
      plugins?: VitePluginLike[]
      server?: { watch?: { ignored?: string[] } }
    }
  }): void
  injectScript(stage: 'head-inline' | 'page' | 'page-ssr' | string, content: string): void
}

interface VitePluginLike {
  name: string
  enforce?: 'pre' | 'post'
  apply?: 'serve' | 'build' | ((this: unknown, config: unknown, env: unknown) => boolean)
  transform?: ViteTransformHandler | {
    order: 'pre' | 'post'
    handler: ViteTransformHandler
  }
  hotUpdate?: {
    order: 'pre' | 'post'
    handler: ViteHotUpdateHandler
  }
}

type ViteTransformHandler = (code: string, id: string) => { code: string; map?: unknown } | null | Promise<{ code: string; map?: unknown } | null>

/** Public Vite environment APIs used to compile before HMR notifications. */
interface ViteEnvironmentLike {
  config: { consumer: 'client' | 'server' }
  moduleGraph: { getModuleById(id: string): { url: string } | undefined }
  transformRequest(url: string): Promise<unknown>
}

type ViteHotUpdateHandler = (
  this: { environment: Pick<ViteEnvironmentLike, 'config'> },
  options: {
    type: 'create' | 'update' | 'delete'
    file: string
    server: { environments: Record<string, ViteEnvironmentLike> }
  },
) => Promise<void>

export interface AstroVisualEditorIntegration {
  name: string
  hooks: {
    'astro:config:setup'?: (ctx: AstroConfigSetupContext) => void | Promise<void>
  }
}

interface AstroNode {
  type: string
  name?: string
  attributes?: readonly { name: string }[]
  children?: readonly AstroNode[]
  position?: { start?: { offset?: number; line?: number; column?: number } }
}

interface ElementEdit {
  offset: number
  attributes: string
}

const EXCLUDED_ELEMENTS = new Set(['script', 'slot', 'style'])

function escapeAttribute(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
}

/** Convert UTF-8 byte offsets reported by Astro into UTF-16 string indices. */
function byteOffsetsToUtf16Indexes(code: string, offsets: readonly number[]): Map<number, number> {
  const bytes = Buffer.from(code, 'utf8')
  const indexes = new Map<number, number>()
  let previousOffset = 0
  let utf16Index = 0
  for (const offset of [...new Set(offsets)].sort((left, right) => left - right)) {
    utf16Index += bytes.subarray(previousOffset, offset).toString('utf8').length
    indexes.set(offset, utf16Index)
    previousOffset = offset
  }
  return indexes
}

function collectElementAnnotations(node: AstroNode, sourceFile: string, edits: ElementEdit[], revision?: string): void {
  const isLiteralElement = node.type === 'element' || node.type === 'custom-element'
  const hasAnnotation = node.attributes?.some(attribute => attribute.name === 'data-dsh-source-file') ?? false
  const start = node.position?.start
  if (isLiteralElement && node.name !== undefined && !EXCLUDED_ELEMENTS.has(node.name)
    && !hasAnnotation && start?.offset !== undefined && start.line !== undefined) {
    edits.push({
      offset: start.offset + Buffer.byteLength(`<${node.name}`, 'utf8'),
      attributes: ` data-dsh-source-file="${escapeAttribute(sourceFile)}" data-dsh-source-loc="${start.line}:${start.column ?? 0}"${revision === undefined ? '' : ` data-dsh-source-hash="${revision}"`}`,
    })
  }
  for (const child of node.children ?? []) collectElementAnnotations(child, sourceFile, edits, revision)
}

function isPrimaryAstroRequest(id: string): boolean {
  return id.endsWith('.astro') && !id.includes('?')
}

/** Never annotate JavaScript already generated by Astro's HMR pipeline. */
function isCompiledAstroOutput(code: string): boolean {
  return code.includes('$$render')
    || code.includes('$$maybeRenderHead')
    || code.includes('$$addAttribute')
    || code.includes('$$createComponent')
}

/** Normalize a filesystem path to a forward-slash project-relative path. */
function toProjectRelative(root: string, id: string): string {
  return relative(root, id).replaceAll('\\', '/')
}

function dshSourceAnnotationsPlugin(projectRoot: string): VitePluginLike {
  return {
    name: 'dsh:astro-source-annotations',
    enforce: 'pre',
    apply: 'serve',
    hotUpdate: {
      order: 'pre',
      async handler({ type, file, server }) {
        if (type !== 'update' || !isPrimaryAstroRequest(file) || this.environment.config.consumer !== 'client') return
        // Astro compares its annotated compile input with raw ctx.read() and
        // misses the CSS-only fast path. Its virtual CSS modules can then load
        // the previous compile metadata before a page reload compiles the file.
        // Vite has already invalidated the changed module: compile it now, in
        // server environments, before Astro/Vite notify the browser. This also
        // refreshes source locations when an edit inserts/removes lines. Run
        // from the client hook so compile failures reach its error overlay.
        for (const environment of Object.values(server.environments)) {
          if (environment.config.consumer !== 'server') continue
          const module = environment.moduleGraph.getModuleById(file)
          if (module !== undefined) await environment.transformRequest(module.url)
        }
      },
    },
    transform: {
      order: 'pre',
      async handler(code, id) {
        if (!isPrimaryAstroRequest(id) || isCompiledAstroOutput(code)) return null
        const { ast } = await parseAstro(code, { position: true })
        const sourceFile = toProjectRelative(projectRoot, id)
        const edits: ElementEdit[] = []
        collectElementAnnotations(ast as unknown as AstroNode, sourceFile, edits, createHash('sha256').update(code).digest('hex'))
        if (edits.length === 0) return null
        const output = new MagicString(code)
        const indexes = byteOffsetsToUtf16Indexes(code, edits.map(edit => edit.offset))
        for (const edit of [...edits].reverse()) {
          output.appendLeft(indexes.get(edit.offset) ?? edit.offset, edit.attributes)
        }
        return { code: output.toString(), map: output.generateMap({ hires: true, source: id, includeContent: true }) }
      },
    },
  }
}

export {
  byteOffsetsToUtf16Indexes,
  collectElementAnnotations,
  dshSourceAnnotationsPlugin,
  escapeAttribute,
  isCompiledAstroOutput,
  isPrimaryAstroRequest,
  toProjectRelative,
}

/** Build the inert bootstrap injected into every development page. */
function buildBootstrap(config: Required<DshVisualEditorOptions>, projectName: string): string {
  const payload = JSON.stringify({ host: config.host, projectRoot: config.projectRoot, name: projectName })
  return [
    '(function () {',
    '  var editorQuery = new URLSearchParams(window.location.search).get("dsh-visual-editor") === "1";',
    '  var editorFrame = window.name === "dsh-visual-editor";',
    '  if (!editorQuery && !editorFrame) return;',
    "  if (document.querySelector('meta[name=\"dsh-visual-editor\"]')) return;",
    '  var meta = document.createElement("meta");',
    '  meta.name = "dsh-visual-editor";',
    `  meta.content = ${JSON.stringify(payload)};`,
    '  document.head.appendChild(meta);',
    `  var src = ${JSON.stringify(config.host)} + "/astro-visual-editor/picker.js?v=annotations-v1";`,
    '  var script = document.createElement("script");',
    '  script.src = src;',
    '  script.async = true;',
    '  script.onerror = function () {};',
    '  document.head.appendChild(script);',
    '})();',
  ].join('\n')
}

export { buildBootstrap }

/** Create the development-only Astro integration. */
export function astroVisualEditor(options: DshVisualEditorOptions = {}): AstroVisualEditorIntegration {
  const projectRoot = resolve(options.projectRoot ?? process.env.DSH_VISUAL_EDITOR_PROJECT_ROOT ?? process.cwd())
  const host = (options.host ?? process.env.DSH_VISUAL_EDITOR_HOST ?? DEFAULT_DSH_HOST).replace(/\/+$/u, '')
  const projectName = basename(projectRoot)

  return {
    name: 'dsh-astro-visual-editor',
    hooks: {
      'astro:config:setup'(ctx) {
        if (ctx.command !== 'dev') return
        ctx.updateConfig({
          vite: {
            plugins: [dshSourceAnnotationsPlugin(projectRoot)],
            server: { watch: { ignored: [...DSH_ATOMIC_WRITE_WATCH_IGNORES] } },
          },
        })
        ctx.injectScript('head-inline', buildBootstrap({ projectRoot, host }, projectName))
      },
    },
  }
}

export default astroVisualEditor
